initial_users = [
    "UTER5GXFW",    # Zargham
    "U06LVP5NMHT",  # Lee
    "U01672057BN",  # Ellie
    "U04SDK8LGUX",  # Brooke
    "U0319V81YGY",  # David
    "U01G7NSR78S",  # Luke
    "U040A3QQKB6",  # Case
    # generated by data policy
    "UMN7U5C8M",
    "UQLHN9CVB",
    "U01672057BN",  # Ellie
    "U01G7NSR78S",  # Luke
    "U01QS7HGP55",
    "U01RA9H74RJ",
    "U0319V81YGY",  # David
    "U038V5LNL9E",
    "U040A3QQKB6",  # Case
    "U04FK8PUDAR",
    "U04SDK8LGUX",  # Brooke
    "U06D411CQ2J",
    "U06LVP5NMHT",  # Lee
]

allowed_channels = [
    # "C077AFMMFGX",  # koi-testing
    # "C06LAQNLVNK",  # koi-tank
    "C04P6EGUYA3",  # attentionecon
    "C04FU2ZGTT9",  # board
    "C0175M3GLSU",  # govbase-labs
    "C06DMGNV7E0",  # koi-pond
]